//! Versioned Core HTTP and WebSocket endpoints.

pub use bts_compat::{
    CORE_ADDONS_PATH, CORE_API_VERSION, CORE_ASSET_PATH, CORE_ASSETS_PATH, CORE_EVENTS_PATH,
    CORE_EVENTS_WEBSOCKET_PATH, CORE_STATE_PATH, CORE_TERMINAL_EVENTS_WEBSOCKET_PATH,
    CORE_TERMINALS_WEBSOCKET_PATH, LOCAL_CORE_HTTP_URL, LOCAL_CORE_TERMINAL_WEBSOCKET_URL,
    LOCAL_CORE_WEBSOCKET_URL,
};
