//! Versioned Core HTTP and WebSocket endpoints.

pub use bts_compat::{
    CORE_ADDONS_PATH, CORE_ADMIN_ADDON_ENABLED_PATH, CORE_ADMIN_ADDON_PATH, CORE_ADMIN_ADDONS_PATH,
    CORE_ADMIN_BASE_PATH, CORE_ADMIN_GROUP_MEMBERS_PATH, CORE_ADMIN_GROUP_NAME_PATH,
    CORE_ADMIN_GROUP_PATH, CORE_ADMIN_GROUPS_PATH, CORE_ADMIN_STATE_PATH, CORE_ADMIN_STATUS_PATH,
    CORE_ADMIN_TERMINAL_DESCRIPTION_PATH, CORE_ADMIN_TERMINAL_NAME_PATH, CORE_ADMIN_TERMINAL_PATH,
    CORE_ADMIN_TERMINAL_TAGS_PATH, CORE_ADMIN_TERMINALS_PATH, CORE_API_DISCOVERY_PATH,
    CORE_API_VERSION, CORE_ASSET_PATH, CORE_ASSETS_PATH, CORE_EVENTS_PATH,
    CORE_EVENTS_WEBSOCKET_PATH, CORE_STATE_PATH, CORE_TELEPHONY_TARGETS_PATH,
    CORE_TERMINAL_EVENTS_WEBSOCKET_PATH, CORE_TERMINALS_WEBSOCKET_PATH, LOCAL_CORE_HTTP_URL,
    LOCAL_CORE_TERMINAL_WEBSOCKET_URL, LOCAL_CORE_WEBSOCKET_URL,
};
